# Generated by Django 6.0.4 on 2026-05-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cattle_id", models.CharField(max_length=100, unique=True)),
                ("rfid_tag", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("device_name", models.CharField(max_length=200)),
                (
                    "device_type",
                    models.CharField(
                        choices=[("collar", "Collar"), ("ear_tag", "Ear Tag")],
                        max_length=50,
                    ),
                ),
                ("firmware_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("body_temperature", models.FloatField()),
                ("heart_rate", models.IntegerField()),
                ("respiratory_rate", models.IntegerField()),
                ("steps", models.IntegerField()),
                ("activity_duration_minutes", models.IntegerField()),
                ("activity_level", models.CharField(max_length=50)),
                ("rumination_duration_minutes", models.IntegerField()),
                ("rumination_episodes", models.IntegerField()),
                ("rumination_quality", models.CharField(max_length=50)),
                ("eating_duration_minutes", models.IntegerField()),
                ("lying_duration_minutes", models.IntegerField()),
                ("standing_duration_minutes", models.IntegerField()),
                ("walking_duration_minutes", models.IntegerField()),
                ("milk_yield_liters", models.FloatField()),
                ("milk_conductivity", models.FloatField()),
                ("feeding_efficiency_percent", models.FloatField()),
                ("feed_intake_estimated", models.BooleanField()),
                ("battery_level_percent", models.IntegerField()),
                ("signal_strength_percent", models.IntegerField()),
                ("gps_accuracy", models.CharField(max_length=50)),
                ("quality_score", models.CharField(max_length=50)),
                ("data_points_received", models.IntegerField()),
                ("data_points_expected", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cattle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.cattle",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.device",
                    ),
                ),
            ],
        ),
    ]
